In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [9]:
train

Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        0            8.0              0.50         0.39            2.20   
1        1            9.3              0.30         0.73            2.30   
2        2            7.1              0.51         0.03            2.10   
3        3            8.1              0.87         0.22            2.60   
4        4            8.5              0.36         0.30            2.30   
...    ...            ...               ...          ...             ...   
2051  2051            6.6              0.31         0.13            2.00   
2052  2052            9.7              0.59         0.21            1.80   
2053  2053            7.7              0.43         0.42            1.70   
2054  2054            9.1              0.50         0.00            1.75   
2055  2055            6.2              0.31         0.18            2.30   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.073                 30.0                  39.0  0.99572  3.33   
1         0.092                 30.0                  67.0  0.99854  3.32   
2         0.059                  3.0                  12.0  0.99660  3.52   
3         0.084                 11.0                  65.0  0.99730  3.20   
4         0.079                 10.0                  45.0  0.99444  3.20   
...         ...                  ...                   ...      ...   ...   
2051      0.056                 29.0                  42.0  0.99388  3.52   
2052      0.079                 27.0                  65.0  0.99745  3.14   
2053      0.071                 19.0                  37.0  0.99258  3.32   
2054      0.058                  5.0                  13.0  0.99670  3.22   
2055      0.059                 12.0                  28.0  0.99520  3.56   

      sulphates  alcohol  quality  
0          0.77     12.1        6  
1          0.67     12.8        6  
2          0.73     11.3        7  
3          0.53      9.8        5  
4          1.36      9.5        6  
...         ...      ...      ...  
2051       0.87     12.0        7  
2052       0.58      9.4        5  
2053       0.77     12.5        8  
2054       0.42      9.5        5  
2055       0.88     11.4        7  

[2056 rows x 13 columns]

In [7]:
test

Id  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     2056            7.2             0.510         0.01             2.0   
1     2057            7.2             0.755         0.15             2.0   
2     2058            8.4             0.460         0.40             2.0   
3     2059            8.0             0.470         0.40             1.8   
4     2060            6.5             0.340         0.32             2.1   
...    ...            ...               ...          ...             ...   
1367  3423            8.8             0.745         0.18             2.7   
1368  3424           15.6             0.240         0.55             2.9   
1369  3425            7.3             0.760         0.00             2.2   
1370  3426            7.6             0.780         0.26             2.6   
1371  3427            8.8             0.780         0.22             3.0   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.077                 31.0                  54.0  0.99748  3.39   
1         0.102                 14.0                  35.0  0.99586  3.33   
2         0.065                 21.0                  50.0  0.99774  3.08   
3         0.056                 14.0                  25.0  0.99480  3.30   
4         0.044                  8.0                  94.0  0.99356  3.23   
...         ...                  ...                   ...      ...   ...   
1367      0.084                 41.0                 115.0  0.99823  3.38   
1368      0.062                 11.0                  25.0  0.99724  2.99   
1369      0.095                  6.0                  19.0  0.99880  3.67   
1370      0.118                 17.0                 104.0  0.99616  3.30   
1371      0.085                 21.0                  43.0  0.99790  3.37   

      sulphates  alcohol  
0          0.59      9.8  
1          0.68     10.0  
2          0.65      9.5  
3          0.65     11.7  
4          0.48     12.8  
...         ...      ...  
1367       0.70      9.8  
1368       0.77     10.1  
1369       0.60      9.4  
1370       0.53      9.9  
1371       0.56     10.2  

[1372 rows x 12 columns]

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [56]:
X = train.iloc[:, 1:-1].values

In [57]:
X

array([[ 8.  ,  0.5 ,  0.39, ...,  3.33,  0.77, 12.1 ],
       [ 9.3 ,  0.3 ,  0.73, ...,  3.32,  0.67, 12.8 ],
       [ 7.1 ,  0.51,  0.03, ...,  3.52,  0.73, 11.3 ],
       ...,
       [ 7.7 ,  0.43,  0.42, ...,  3.32,  0.77, 12.5 ],
       [ 9.1 ,  0.5 ,  0.  , ...,  3.22,  0.42,  9.5 ],
       [ 6.2 ,  0.31,  0.18, ...,  3.56,  0.88, 11.4 ]])

In [71]:
y = train.iloc[:, -1].values

In [59]:
y

array([6, 6, 7, ..., 8, 5, 7], dtype=int64)

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [61]:
fRegressor = RandomForestRegressor(n_estimators=200)

In [62]:
fRegressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200)

In [63]:
r2_score(y_test, fRegressor.predict(X_test))

0.21869800349150914

In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
lin_reg = LinearRegression()
lin_reg.fit(X, y)

LinearRegression()

In [97]:
r2_score(y_test, (lin_reg.predict(X_test)))

-0.09195365814950018

In [51]:
testId = test.iloc[:, 0].values

In [52]:
testId

array([2056, 2057, 2058, ..., 3425, 3426, 3427], dtype=int64)

In [53]:
test_data = test.iloc[:, 1:].values

In [54]:
test_data

array([[7.20e+00, 5.10e-01, 1.00e-02, ..., 3.39e+00, 5.90e-01, 9.80e+00],
       [7.20e+00, 7.55e-01, 1.50e-01, ..., 3.33e+00, 6.80e-01, 1.00e+01],
       [8.40e+00, 4.60e-01, 4.00e-01, ..., 3.08e+00, 6.50e-01, 9.50e+00],
       ...,
       [7.30e+00, 7.60e-01, 0.00e+00, ..., 3.67e+00, 6.00e-01, 9.40e+00],
       [7.60e+00, 7.80e-01, 2.60e-01, ..., 3.30e+00, 5.30e-01, 9.90e+00],
       [8.80e+00, 7.80e-01, 2.20e-01, ..., 3.37e+00, 5.60e-01, 1.02e+01]])

In [99]:
pred = (fRegressor.predict(test_data))

In [100]:
#Round the predictions to int
pred = (pred).astype(int)

In [101]:
#Create a dataframe with the id and the predicted values
submission = pd.DataFrame({'Id':testId, 'quality':pred})

In [102]:
submission

Id  quality
0     2056        5
1     2057        6
2     2058        5
3     2059        6
4     2060        5
...    ...      ...
1367  3423        5
1368  3424        6
1369  3425        5
1370  3426        5
1371  3427        5

[1372 rows x 2 columns]

In [103]:
#Save the dataframe to a csv file
submission.to_csv('submission.csv', index=False)